import { UIView, UIColor, UIImage, UIImageView, UIButton, UIControl, UILabel , NSTextAlignment } from 'UIKit'
import { CGRect } from 'CoreFoundation';
import { DispatchQueue.main } from 'Dispatch';
import { Selector } from 'ObjectiveC';


export const setCustomUI = (customAreaView : UIView) =>{
	customView.setCustomUI(customAreaView)
}

class customView {
	static setCustomUI(customAreaView : UIView) {
		DispatchQueue.main.async(execute = () : void => {

			// 创建view
			// let view = new UIView()
			// view.backgroundColor = UIColor.red
			// view.frame = new CGRect(x = 90, y = 120, width = 100, height = 100)
			// customAreaView.addSubview(view)

			// 创建imageView
			// let imageView = new UIImageView()
			// imageView.image = new UIImage(named = "back-7.png")
			// imageView.backgroundColor = UIColor.red
			// imageView.frame = new CGRect(x = 90, y = 320, width = 100, height = 100)
			// customAreaView.addSubview(imageView)

			// 创建label
			// let label = new UILabel()
			// label.text = "自定义view"
			// label.textColor = UIColor.red
			// label.frame = new CGRect(x = 90, y = 420, width = 100, height = 100)
			// customAreaView.addSubview(label)

			// let btn = new UIButton(type = UIButton.ButtonType.custom)
			// btn.frame = new CGRect(x = 90, y = 520, width = 100, height = 100)
			// btn.setTitle("点击", for = UIControl.State.normal)
			// const method = new Selector("clickEvent")
			// btn.addTarget(this, action = method, for = UIControl.Event.touchUpInside)
			// customAreaView.addSubview(btn)
		})

		
	}
	@objc static clickEvent() {
		// 回调
		console.log("调用了---")
	}
}

export class CLToast {
	static getContentView():UIView{
		let keyWindow = UTSiOS.getKeyWindow()
		let contentView = new UIView()
		contentView.tag = 1100
		contentView.center = keyWindow.center
		contentView.backgroundColor = UTSiOS.colorWithString('#FFFFFF')
		contentView.bounds = new CGRect(x = 0, y=0,width = 300, height = 200)
		contentView.layer.cornerRadius = 15;
		keyWindow.addSubview(contentView)
		return contentView
	}
	
	static makeToast(message: string){
		let contentView = CLToast.getContentView()
		let label = new UILabel()
		label.text = "自定义view"
		label.textColor = UIColor.red
		label.textAlignment = NSTextAlignment.center
		label.frame = new CGRect(x = 0, y = 0, width = 300, height = 200)
		contentView.addSubview(label)
		
		// DispatchQueue.main.asyncAfter(deadline = Date.now() + 2.0) {
		//     contentView.removeFromSuperview()
		// }
		
	}
}